### ISSUE TITLE
Custom element doesn't exist: grid-layout

### ISSUE THREAD

**Issue by MarkGiesing01** [sagaland93/hass-config#1]
Dear Sagaland93,

I really like your version of Matt8707's dashboard and i would like to implement it to my HA, but I always get the custom element error. What can I do? Where can i find the implementation of the hacs frontend cards?

Thank you in advance.
Mark Giesing

**Comment by sagaland93** [comment]
Hi Mark,

Have you installed this?
https://github.com/thomasloven/lovelace-layout-card

**Comment by MarkGiesing01** [comment]
I installed the layout-card, button-card, swipe-card and card-mod. 

Should I add something like this in the config file like matt8707 his config?

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,  type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /hacsfiles/tabbed-card/tabbed-card.js,                                 type: module },

      { url: '/local/marked.min.js?v=4.2.5',                                        type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.8.0',                                  type: module },
      { url: '/local/browser_mod_icon.js?v=0.5',                                    type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

**Comment by sagaland93** [comment]
You might have to do that, although I have not. It should be added automatically if you're using HACS.

Try following this:
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by MarkGiesing01** [comment]
I added it manualy to my the resources and its working now! Thanks!
