### ISSUE TITLE
Template: weather_forecast

### ISSUE THREAD

**Issue by frozenhellguard** [sagaland93/hass-config#2]
Hello! I'm actually using the original (matt's) config with a quite a few tweaks myself, so I understand fully if you do not wish to help me with this issue. I'm trying to get your weather_forecast template to work, but it's not showing my card at all (just leaving a blank space where the card is meant to go). I've implemented your template into my custom ones but I must be missing something here. I'm also using the PirateWeather integration. Any help would be appreciated!

**Comment by frozenhellguard** [comment]
It's the sensor (variable) for current_weather I am missing, I think.

**Comment by sagaland93** [comment]
Sounds like you're on the right track. But yes, the variables must be defined.
When they're defined as empty like this, they must be defined somewhere else in order to have a value.


      temp_min: ''
      temp_max: ''
      current_weather: ''


Like the following

          - type: custom:button-card
            entity: weather.pirateweather
            name: My location
            tap_action:
              !include popup/weather.yaml
            template:
              - base
              - weather_forecast
            variables:
              temp_min: sensor.weather_min_temp
              temp_max: sensor.weather_max_temp
              current_weather: sensor.pirateweather_hourly_summary

**Comment by frozenhellguard** [comment]
Perfect, I managed to get it working now. Thanks alot for your help and great work with your version of it! :)
